//
//  AnalyzedResponse.swift
//  iantha
//
//  Created by Taylor Meek on 4/4/23.
//

import Foundation

struct AnalyzedResponse {
    /// A String containing the original input text provided to the GPT-3 model.
    let inputText: String
    /// A String containing the output text generated by the GPT-3 model as a response.
    let outputText: String
    /// A Double representing the confidence score for the generated response, ranging from 0 to 1.
    let confidence: Double
    
    /// Initializes a new AnalyzedResponse with the specified input text, output text, and confidence.
    ///
    /// - Parameters:
    ///   - inputText: The original input text provided to the GPT-3 model.
    ///   - outputText: The output text generated by the GPT-3 model as a response.
    ///   - confidence: The confidence score for the generated response, ranging from 0 to 1.
    init(inputText: String, outputText: String, confidence: Double) {
        self.inputText = inputText
        self.outputText = outputText
        self.confidence = confidence
    }
}
